env:
    global:
        - secure: hO3muck3cWHMhL7hS6OYeYEGL56qE9p8YSHJgKLYF4o+QN7O8imKWlKMTrBe/pKEHVylO3n8bnsDw2+pGVK6FkDvsdiJAPhq5Cx1Hd9R4SjvkKC2Sn9ypT/3CM1wPi6DcawVTuAFleNlc5NujI/ToXonXWQ0D4nimNAdCKntdgMbFs1YbQxVADnW7pbii1wusgtiT6xWyWJwcqTXwW5XJofig7cKHO2fYpi/0nWkug+BGhfeOJ6/fC6GbBJ/7azfGB9Nc+hRNhCbMtHJGbTkuupSVtpxk7TuEwnVDYosWQAjJxaWYSM1eJmvysgC+tvMQgw8haGpgY9xni+nu3HrozEgYYnwnh5+N4TZdn4AczrVEs1n2Y82cQp/++OS4X08+B/HWCN5WDzXRx+HOskAyvE1wA9P/payXZeUfRBqs0Z+mBcRcPxPxM7tIUT2lTBbeTjrzb/Qz4t3Iy3WTGG1T84K5YtOLstTGKBpu5LxW++f2rEGbQA7N3v1l0PiT5ZWgqkB4NgoE7wLxXVRqIV+kjSX/C7Gi1dC5EnCU1XCqA9T3USRuB/SGJxhDuw/Gmde1n/Y7SaQnCwgrMPj7LMIF49qYPIf7r6Zb+FVb+pkSbf7LiKNr3DABuDDInBn8UcoXlRMBbxTtvSKLxXds7TN3qFilNj4yizrOGWGdcCFwRU=
language: rust
branches:
    only:
        - master
        - gh-pages
install:
    - sudo curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_libsodium.sh | bash
script:
    - cargo build --verbose
    - cargo test --verbose
after_script: |
  if  [[ $TRAVIS_BRANCH = master ]] && [[ $TRAVIS_PULL_REQUEST = false ]]; then
    cargo doc &&
    echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
    sudo pip install ghp-import &&
    mkdir docs-stage &&
    COMMIT_MSG=$(git log -1 | tr '[:upper:]' '[:lower:]' | grep "version change to " | tr -d ' ') &&
    git clone https://github.com/${TRAVIS_REPO_SLUG}.git  docs-stage &&
    cd docs-stage &&
    git checkout gh-pages;
    rm -rf .git*;
    # lines 24 - 28 is a patch script for handling old gh-pages structure
    OLD_FILE=$(ls | grep "main.js");
    if [[ $OLD_FILE == main* ]]; then
      rm -rf * &&
      echo "<meta http-equiv=refresh content=0;url=master/`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > index.html;
    fi
    if [[ $COMMIT_MSG == versionchangeto* ]];  then
      VERSION=${COMMIT_MSG##*to} &&
      mkdir -p $VERSION &&
      mkdir -p latest &&
      cp -rf ../target/doc/* $VERSION &&
      cp -rf ../target/doc/* latest &&
      git config --global user.email dev@maidsafe.net &&
      git config --global user.name maidsafe-jenkins &&
      git tag $VERSION -a -m "Version $VERSION" &&
      git push -q https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} --tags;
    fi
    mkdir -p master
    cp -rf ../target/doc/* master &&
    cd .. &&
    ghp-import -n docs-stage &&
    git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages;
  fi
