env:
  global:
    - secure: Oi1sYzUwhYNlkbBrnNKYhItOXnG9Ak6fixgIBbOv+gHkKn2vuwMixrdCIKoJMThBJr2nU8bSfeqm4lmTR1xHE69CX/bIfon8EZ0QN3AqzJcjtAU+vRZer9PFYeaIppz/ZuD4k5rs2wjbtjcIPWV8dBAWn0SU2mxj6MMpXYlmNWs=
language: rust
install:
    - wget https://github.com/jedisct1/libsodium/releases/download/1.0.3/libsodium-1.0.3.tar.gz
    - tar xvfz libsodium-1.0.3.tar.gz
    - cd libsodium-1.0.3 && ./configure --prefix=/usr && make && sudo make install && cd ..
script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo doc
    - mv target/doc doc
after_script:
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
