[package]
name = "sodiumoxide"
description = "Fast cryptographic library for Rust (bindings to libsodium)"
documentation = "https://dnaq.github.io/sodiumoxide_doc"
repository = "https://github.com/dnaq/sodiumoxide"
readme = "README.md"
keywords = ["crypto", "NaCl", "libsodium"]
version = "0.0.7"
authors = ["dnaq"]
license = "MIT"

[dependencies]
libc = "*"
libsodium-sys = "*"
rustc-serialize = "*"

[features]
benchmarks = []
